server:
  servlet:
    session:
      timeout: 180m # Set session timeout to 180 minutes

spring:
  mvc:
    async:
      request-timeout: 1800000 # Set the asynchronous request timeout to 1800000 milliseconds (30 minutes)