[package]
name = "custom-root-certs"
version = "0.1.0"
authors = ["rcoh@amazon.com>"]
edition = "2021"

description = "An example demonstrating setting a custom root certificate with rustls"

[dependencies]
aws-config = { features = ["behavior-version-latest"], version = "1.0.1"}
# bringing our own HTTPs so no need for the default features
aws-sdk-s3 = "1.2.0"
tokio = { version = "1.21.2", features = ["full"] }
rustls = "0.20.7"
hyper-rustls = { version = "0.23.0", features = ["http2"] }
