[package]
name = "resourceexplorer2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-resourceexplorer2 = { path = "../../../serde-aws-sdk/resourceexplorer2" }