---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check end labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          all_of: status/code-review-complete,status/ready-to-merge
          one_of: status/test-review-complete,status/no-test-review-needed
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  check_text_labels:
    name: Check Text labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: status/text-review-complete,status/no-text-review-needed
          repo_token: ${{ secrets.GITHUB_TOKEN }}
