name: "Lint Labels"

on: [pull_request]

jobs:
  label-linter:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      # The Audit Labels workflow creates, renames, updates
      # or deletes labels based on a list of allowed labels.
      #
      # To use this workflow, you must set up and configure 
      # labels in a .github/allowed-labels.yml file
      #
      # For more information, see:
      # https://github.com/crazy-max/ghaction-github-labeler
      -
        name: Audit Labels
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/allowed-labels.yml
          skip-delete: false
          dry-run: false
