name: PR Commenter

on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Thanks for your contribution! :tada: To speed up the review process, please see our [CONTRIBUTING.md](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/CONTRIBUTING.md) to make sure you did everything correctly. We will review your PR as soon as possible! :heart: 
