name: Pull Request Stats

on:
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: 'awsdocs'
          period: 112
          charts: true
          disableLinks: true
          sortBy: 'COMMENTS'
