name: RuboCop Linting

on:
  pull_request:
  workflow_dispatch:

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install rubocop

      - name: Run RuboCop
        run: rubocop --config ../linters/.ruby-lint.yml .
