name: Rust
on:
  push:
    paths:
      - "rust_dev_preview/**"
    branches:
      - main
  pull_request:
    paths:
      - "rust_dev_preview/**"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pre-setup
        run: sudo apt-get update && sudo apt-get install -y libclang-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Rust format
        run: cargo fmt --manifest-path rust_dev_preview/Cargo.toml --all --check
      - name: Rust lint
        run: cargo clippy --manifest-path rust_dev_preview/Cargo.toml -- -D warnings
      - name: Rust test
        run: cargo test --manifest-path rust_dev_preview/Cargo.toml --all
        env:
          APP_ENVIRONMENT: test
