name: "cpp lint check"
on:
  pull_request:
    paths:
      - "cpp/**"
  workflow_dispatch:

jobs:
  cpplint:
    name: Lint CPP
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            .github/sd-cpp-linter
            cpp
      - name: "Run clang-tidy check"
        uses: ./.github/sd-cpp-linter
        with:
          config_file: ./.github/sd-cpp-linter/clang-tidy-config.txt
          token: ${{ secrets.GITHUB_TOKEN }}
