name: Invoke runTheNumbers lambda function
on:
   pull_request:
        branches: [main]
   push:
        branches: [main]
   workflow_dispatch:
env: 
   COMMIT:  ${{github.sha}}
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: echo "JSON_PAYLOAD={\"commit\" :\"${{ env.COMMIT }}\"}" >> $GITHUB_ENV
        - name: Invoke runTheNumbers
          uses: gagoar/invoke-aws-lambda@master
          with:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             REGION: 'eu-west-1'
             FunctionName: runTheNumbers
             Payload: ${{env.JSON_PAYLOAD}}
             InvocationType: RequestResponse
             LogType: None
