# This workflow executes a Lamdba function that records metrics for each merged PR.
#
# For more information, see:
# https://github.com/marketplace/actions/invoke-aws-lambda

name: Trigger Lambda to capture metrics

permissions:
  contents: read
  id-token: write
  
on:   # yamllint disable-line rule:truthy
  pull_request:
    types:
      - closed
  workflow_dispatch:
env:
  COMMIT: ${{github.event.pull_request.head.sha}}
  PR_AUTHOR: ${{ github.event.pull_request.user.login }}
  AWS_REGION: "eu-west-1"
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: GitHub Statistics
    steps:
      - name: Create payload
        run: echo "JSON_PAYLOAD={\"commit\" :\"${{ env.COMMIT }}\",\"author\" :\"${{ env.PR_AUTHOR }}\"}" >> $GITHUB_ENV
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Invoke Lambda
        uses: y5347M/invoke-aws-lambda-oidc@v1
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: 'arn:aws:iam::959731285276:role/run-the-numbers-lambda'
          function-name: 'runTheNumbers'
          payload: ${{env.JSON_PAYLOAD}}
