name: Invoke runTheNumbers lambda function
on:
   workflow_dispatch:
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: echo "JSON_PAYLOAD={\"commit\":\"${{ github.event.pull_request.base.sha }}\"}" >> $GITHUB_ENV
        - name: Invoke runTheNumbers
          uses: gagoar/invoke-aws-lambda@master
          with:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             REGION: 'eu-west-1'
             FunctionName: runTheNumbers
             Payload: ${{ env.JSON_PAYLOAD }}
