# This workflow executes a Lamdba function that records metrics for each successfully merged PR.
#
# For more information, see:
# https://github.com/marketplace/actions/invoke-aws-lambda

name: Invoke Lambda function for GitHub example/snippet metrics

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - closed
  workflow_dispatch:
env:
  COMMIT: ${{github.event.pull_request.head.sha}}
jobs:
  if_merged: 
    name: Generate Repo Statistics
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Convert event Payload
        run: echo "JSON_PAYLOAD={\"commit\" :\"${{ env.COMMIT }}\"}" >> $GITHUB_ENV
      - name: Invoke 'runTheNumbers' Lambda function
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: 'eu-west-1'
          FunctionName: runTheNumbers
          Payload: ${{env.JSON_PAYLOAD}}
          InvocationType: RequestResponse
          LogType: None
