name: Invoke runTheNumbers lambda function
on:
   workflow_dispatch:
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Invoke runTheNumbers
          uses: gagoar/invoke-aws-lambda@master
          with:
             ref: ${{ github.event.pull_request.base.sha }}
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             REGION: 'eu-west-1'
             FunctionName: runTheNumbers
             Payload: '{ "commit": ref}'
