name: Validate Documentation Metadata

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-doc-metadata:
    name: Validate Doc Metadata
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: validate metadata
        uses: awsdocs/aws-doc-sdk-examples-tools@43597d6fced6b8e92533c84158b6fbcf91219be4
