name: Validate Documentation Metadata
on:
  pull_request:
  # run on demand
  workflow_dispatch:
jobs:
  validate-doc-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python 3.9.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      - name: Install dependencies
        run: |
          python -m pip install yamale
      - name: Validate metadata with yamale
        run: python .doc_gen/validation/validate_doc_metadata.py .doc_gen
